runtime: nodejs
env: flex
service: ipg-dev-bknd
env_variables:
    APP_PORT: "8080"
    NODE_ENV: "dev"
    DB_HOST: "35.238.3.80"
    DB_PORT: "5432"
    DB_USERNAME: "postgres"
    DB_PASSWORD: "HoB4G2PqpsKxCGom"
    DB_NAME: "postgres"
    AZURE_CLIENT_ID: "8e702bce-44fe-4897-b356-b4354098b9bc"
    AZURE_TENANT_ID: "d026e4c1-5892-497a-b9da-ee493c9f0364"
    AZURE_AUTH_URL: "https://login.microsoftonline.com"
    AZURE_CLIENT_SECRET: "4cbY6K21xNEPDt1DHz..pC0-.d1Fv2n5Az"
    MICROSOFT_GRAPH_URL: "https://graph.microsoft.com/v1.0"
    MICROSOFT_GRAPH_SCOPE: "https://graph.microsoft.com/.default"
    GOOGLE_MAPS_API_KEY: "AIzaSyC6vsYfGjFz6mZdc9Lg1khTOu4zSigETLU"
    NOTIFICATION_SERVICE_URL: "https://ipg-dev-notif-dot-ipg-internal.uc.r.appspot.com"
    JWT_SECRET: 1234567890
    WEBSITES_HOST: "https://ipg-frontend.zazmicdemo.com"
manual_scaling:
    instances: 1
resources:
    cpu: 1
    memory_gb: 1
    disk_size_gb: 20
